# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email address')),
                ('avatar_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Avatar Url')),
                ('gravatar_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Gravatar Url')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url')),
                ('html_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Html Url')),
                ('followers_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Followers Url')),
                ('following_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Following Url')),
                ('gists_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Gists Url')),
                ('starred_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Starred Url')),
                ('subscriptions_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subscriptions Url')),
                ('organizations_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Organizations Url')),
                ('repos_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Repos Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d')),
            ],
        ),
    ]
