# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'User Added Summary',
                'verbose_name_plural': 'Users Added Summary',
            },
            bases=('app.userdetails',),
        ),
        migrations.CreateModel(
            name='HitsSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'Hits Summary',
                'verbose_name_plural': 'Hits Summary',
            },
            bases=('app.hits',),
        ),
    ]
