# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hits_hitssummary_usersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='repos_url',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='repos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repos'),
        ),
    ]
