# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-10 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180703_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location'),
        ),
    ]
