# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdetails_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='followers_url',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='followers',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Followers'),
        ),
    ]
